// <auto-generated />
namespace WebApplication_brr_bmi1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class yangisam : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(yangisam));
        
        string IMigrationMetadata.Id
        {
            get { return "201905232022475_yangisam"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
